[build-system]
requires = ["wheel","setuptools", "numpy>=2.0.0rc1"]
dependencies = ["oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3{8,9,10,11,12}-*" 
