# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _CSF_3DFin
else:
    import _CSF_3DFin

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CSF_3DFin.delete_SwigPyIterator

    def value(self):
        return _CSF_3DFin.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _CSF_3DFin.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _CSF_3DFin.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _CSF_3DFin.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _CSF_3DFin.SwigPyIterator_equal(self, x)

    def copy(self):
        return _CSF_3DFin.SwigPyIterator_copy(self)

    def next(self):
        return _CSF_3DFin.SwigPyIterator_next(self)

    def __next__(self):
        return _CSF_3DFin.SwigPyIterator___next__(self)

    def previous(self):
        return _CSF_3DFin.SwigPyIterator_previous(self)

    def advance(self, n):
        return _CSF_3DFin.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _CSF_3DFin.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _CSF_3DFin.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _CSF_3DFin.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _CSF_3DFin.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _CSF_3DFin.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _CSF_3DFin.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _CSF_3DFin:
_CSF_3DFin.SwigPyIterator_swigregister(SwigPyIterator)

class VecInt(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _CSF_3DFin.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CSF_3DFin.VecInt___nonzero__(self)

    def __bool__(self):
        return _CSF_3DFin.VecInt___bool__(self)

    def __len__(self):
        return _CSF_3DFin.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _CSF_3DFin.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CSF_3DFin.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CSF_3DFin.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CSF_3DFin.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CSF_3DFin.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CSF_3DFin.VecInt___setitem__(self, *args)

    def pop(self):
        return _CSF_3DFin.VecInt_pop(self)

    def append(self, x):
        return _CSF_3DFin.VecInt_append(self, x)

    def empty(self):
        return _CSF_3DFin.VecInt_empty(self)

    def size(self):
        return _CSF_3DFin.VecInt_size(self)

    def swap(self, v):
        return _CSF_3DFin.VecInt_swap(self, v)

    def begin(self):
        return _CSF_3DFin.VecInt_begin(self)

    def end(self):
        return _CSF_3DFin.VecInt_end(self)

    def rbegin(self):
        return _CSF_3DFin.VecInt_rbegin(self)

    def rend(self):
        return _CSF_3DFin.VecInt_rend(self)

    def clear(self):
        return _CSF_3DFin.VecInt_clear(self)

    def get_allocator(self):
        return _CSF_3DFin.VecInt_get_allocator(self)

    def pop_back(self):
        return _CSF_3DFin.VecInt_pop_back(self)

    def erase(self, *args):
        return _CSF_3DFin.VecInt_erase(self, *args)

    def __init__(self, *args):
        _CSF_3DFin.VecInt_swiginit(self, _CSF_3DFin.new_VecInt(*args))

    def push_back(self, x):
        return _CSF_3DFin.VecInt_push_back(self, x)

    def front(self):
        return _CSF_3DFin.VecInt_front(self)

    def back(self):
        return _CSF_3DFin.VecInt_back(self)

    def assign(self, n, x):
        return _CSF_3DFin.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _CSF_3DFin.VecInt_resize(self, *args)

    def insert(self, *args):
        return _CSF_3DFin.VecInt_insert(self, *args)

    def reserve(self, n):
        return _CSF_3DFin.VecInt_reserve(self, n)

    def capacity(self):
        return _CSF_3DFin.VecInt_capacity(self)
    __swig_destroy__ = _CSF_3DFin.delete_VecInt

# Register VecInt in _CSF_3DFin:
_CSF_3DFin.VecInt_swigregister(VecInt)

class VecFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _CSF_3DFin.VecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CSF_3DFin.VecFloat___nonzero__(self)

    def __bool__(self):
        return _CSF_3DFin.VecFloat___bool__(self)

    def __len__(self):
        return _CSF_3DFin.VecFloat___len__(self)

    def __getslice__(self, i, j):
        return _CSF_3DFin.VecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CSF_3DFin.VecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CSF_3DFin.VecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CSF_3DFin.VecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CSF_3DFin.VecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CSF_3DFin.VecFloat___setitem__(self, *args)

    def pop(self):
        return _CSF_3DFin.VecFloat_pop(self)

    def append(self, x):
        return _CSF_3DFin.VecFloat_append(self, x)

    def empty(self):
        return _CSF_3DFin.VecFloat_empty(self)

    def size(self):
        return _CSF_3DFin.VecFloat_size(self)

    def swap(self, v):
        return _CSF_3DFin.VecFloat_swap(self, v)

    def begin(self):
        return _CSF_3DFin.VecFloat_begin(self)

    def end(self):
        return _CSF_3DFin.VecFloat_end(self)

    def rbegin(self):
        return _CSF_3DFin.VecFloat_rbegin(self)

    def rend(self):
        return _CSF_3DFin.VecFloat_rend(self)

    def clear(self):
        return _CSF_3DFin.VecFloat_clear(self)

    def get_allocator(self):
        return _CSF_3DFin.VecFloat_get_allocator(self)

    def pop_back(self):
        return _CSF_3DFin.VecFloat_pop_back(self)

    def erase(self, *args):
        return _CSF_3DFin.VecFloat_erase(self, *args)

    def __init__(self, *args):
        _CSF_3DFin.VecFloat_swiginit(self, _CSF_3DFin.new_VecFloat(*args))

    def push_back(self, x):
        return _CSF_3DFin.VecFloat_push_back(self, x)

    def front(self):
        return _CSF_3DFin.VecFloat_front(self)

    def back(self):
        return _CSF_3DFin.VecFloat_back(self)

    def assign(self, n, x):
        return _CSF_3DFin.VecFloat_assign(self, n, x)

    def resize(self, *args):
        return _CSF_3DFin.VecFloat_resize(self, *args)

    def insert(self, *args):
        return _CSF_3DFin.VecFloat_insert(self, *args)

    def reserve(self, n):
        return _CSF_3DFin.VecFloat_reserve(self, n)

    def capacity(self):
        return _CSF_3DFin.VecFloat_capacity(self)
    __swig_destroy__ = _CSF_3DFin.delete_VecFloat

# Register VecFloat in _CSF_3DFin:
_CSF_3DFin.VecFloat_swigregister(VecFloat)

class VecVecFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _CSF_3DFin.VecVecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CSF_3DFin.VecVecFloat___nonzero__(self)

    def __bool__(self):
        return _CSF_3DFin.VecVecFloat___bool__(self)

    def __len__(self):
        return _CSF_3DFin.VecVecFloat___len__(self)

    def __getslice__(self, i, j):
        return _CSF_3DFin.VecVecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CSF_3DFin.VecVecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CSF_3DFin.VecVecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CSF_3DFin.VecVecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CSF_3DFin.VecVecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CSF_3DFin.VecVecFloat___setitem__(self, *args)

    def pop(self):
        return _CSF_3DFin.VecVecFloat_pop(self)

    def append(self, x):
        return _CSF_3DFin.VecVecFloat_append(self, x)

    def empty(self):
        return _CSF_3DFin.VecVecFloat_empty(self)

    def size(self):
        return _CSF_3DFin.VecVecFloat_size(self)

    def swap(self, v):
        return _CSF_3DFin.VecVecFloat_swap(self, v)

    def begin(self):
        return _CSF_3DFin.VecVecFloat_begin(self)

    def end(self):
        return _CSF_3DFin.VecVecFloat_end(self)

    def rbegin(self):
        return _CSF_3DFin.VecVecFloat_rbegin(self)

    def rend(self):
        return _CSF_3DFin.VecVecFloat_rend(self)

    def clear(self):
        return _CSF_3DFin.VecVecFloat_clear(self)

    def get_allocator(self):
        return _CSF_3DFin.VecVecFloat_get_allocator(self)

    def pop_back(self):
        return _CSF_3DFin.VecVecFloat_pop_back(self)

    def erase(self, *args):
        return _CSF_3DFin.VecVecFloat_erase(self, *args)

    def __init__(self, *args):
        _CSF_3DFin.VecVecFloat_swiginit(self, _CSF_3DFin.new_VecVecFloat(*args))

    def push_back(self, x):
        return _CSF_3DFin.VecVecFloat_push_back(self, x)

    def front(self):
        return _CSF_3DFin.VecVecFloat_front(self)

    def back(self):
        return _CSF_3DFin.VecVecFloat_back(self)

    def assign(self, n, x):
        return _CSF_3DFin.VecVecFloat_assign(self, n, x)

    def resize(self, *args):
        return _CSF_3DFin.VecVecFloat_resize(self, *args)

    def insert(self, *args):
        return _CSF_3DFin.VecVecFloat_insert(self, *args)

    def reserve(self, n):
        return _CSF_3DFin.VecVecFloat_reserve(self, n)

    def capacity(self):
        return _CSF_3DFin.VecVecFloat_capacity(self)
    __swig_destroy__ = _CSF_3DFin.delete_VecVecFloat

# Register VecVecFloat in _CSF_3DFin:
_CSF_3DFin.VecVecFloat_swigregister(VecVecFloat)

class VecDouble(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _CSF_3DFin.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CSF_3DFin.VecDouble___nonzero__(self)

    def __bool__(self):
        return _CSF_3DFin.VecDouble___bool__(self)

    def __len__(self):
        return _CSF_3DFin.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _CSF_3DFin.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CSF_3DFin.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CSF_3DFin.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CSF_3DFin.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CSF_3DFin.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CSF_3DFin.VecDouble___setitem__(self, *args)

    def pop(self):
        return _CSF_3DFin.VecDouble_pop(self)

    def append(self, x):
        return _CSF_3DFin.VecDouble_append(self, x)

    def empty(self):
        return _CSF_3DFin.VecDouble_empty(self)

    def size(self):
        return _CSF_3DFin.VecDouble_size(self)

    def swap(self, v):
        return _CSF_3DFin.VecDouble_swap(self, v)

    def begin(self):
        return _CSF_3DFin.VecDouble_begin(self)

    def end(self):
        return _CSF_3DFin.VecDouble_end(self)

    def rbegin(self):
        return _CSF_3DFin.VecDouble_rbegin(self)

    def rend(self):
        return _CSF_3DFin.VecDouble_rend(self)

    def clear(self):
        return _CSF_3DFin.VecDouble_clear(self)

    def get_allocator(self):
        return _CSF_3DFin.VecDouble_get_allocator(self)

    def pop_back(self):
        return _CSF_3DFin.VecDouble_pop_back(self)

    def erase(self, *args):
        return _CSF_3DFin.VecDouble_erase(self, *args)

    def __init__(self, *args):
        _CSF_3DFin.VecDouble_swiginit(self, _CSF_3DFin.new_VecDouble(*args))

    def push_back(self, x):
        return _CSF_3DFin.VecDouble_push_back(self, x)

    def front(self):
        return _CSF_3DFin.VecDouble_front(self)

    def back(self):
        return _CSF_3DFin.VecDouble_back(self)

    def assign(self, n, x):
        return _CSF_3DFin.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _CSF_3DFin.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _CSF_3DFin.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _CSF_3DFin.VecDouble_reserve(self, n)

    def capacity(self):
        return _CSF_3DFin.VecDouble_capacity(self)
    __swig_destroy__ = _CSF_3DFin.delete_VecDouble

# Register VecDouble in _CSF_3DFin:
_CSF_3DFin.VecDouble_swigregister(VecDouble)

class Params(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bSloopSmooth = property(_CSF_3DFin.Params_bSloopSmooth_get, _CSF_3DFin.Params_bSloopSmooth_set)
    time_step = property(_CSF_3DFin.Params_time_step_get, _CSF_3DFin.Params_time_step_set)
    class_threshold = property(_CSF_3DFin.Params_class_threshold_get, _CSF_3DFin.Params_class_threshold_set)
    cloth_resolution = property(_CSF_3DFin.Params_cloth_resolution_get, _CSF_3DFin.Params_cloth_resolution_set)
    rigidness = property(_CSF_3DFin.Params_rigidness_get, _CSF_3DFin.Params_rigidness_set)
    interations = property(_CSF_3DFin.Params_interations_get, _CSF_3DFin.Params_interations_set)

    def __init__(self):
        _CSF_3DFin.Params_swiginit(self, _CSF_3DFin.new_Params())
    __swig_destroy__ = _CSF_3DFin.delete_Params

# Register Params in _CSF_3DFin:
_CSF_3DFin.Params_swigregister(Params)

class CSF(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _CSF_3DFin.CSF_swiginit(self, _CSF_3DFin.new_CSF())
    __swig_destroy__ = _CSF_3DFin.delete_CSF

    def readPointsFromFile(self, filename):
        return _CSF_3DFin.CSF_readPointsFromFile(self, filename)

    def getPointCloud(self, *args):
        return _CSF_3DFin.CSF_getPointCloud(self, *args)

    def savePoints(self, grp, path):
        return _CSF_3DFin.CSF_savePoints(self, grp, path)

    def size(self):
        return _CSF_3DFin.CSF_size(self)

    def setPointCloud(self, *args):
        return _CSF_3DFin.CSF_setPointCloud(self, *args)

    def do_filtering(self, groundIndexes, offGroundIndexes, exportCloth=True):
        return _CSF_3DFin.CSF_do_filtering(self, groundIndexes, offGroundIndexes, exportCloth)

    def do_cloth_export(self):
        return _CSF_3DFin.CSF_do_cloth_export(self)
    params = property(_CSF_3DFin.CSF_params_get, _CSF_3DFin.CSF_params_set)
    index = property(_CSF_3DFin.CSF_index_get, _CSF_3DFin.CSF_index_set)

# Register CSF in _CSF_3DFin:
_CSF_3DFin.CSF_swigregister(CSF)



